# Generated by Django 5.0.8 on 2025-04-23 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuestionario', models.CharField(choices=[('KIDSCREEN', 'Genérico de CVRS en niñas, niños y jóvenes'), ('CP-QOL', 'CVRS en personas con discapacidad motora'), ('TWVQ-AR', 'Percepción de la voz y vivencias de mujeres trans'), ('VRBQ', 'Evaluación de rehabilitación de trastornos vestibulares')], default='KIDSCREEN', max_length=20, verbose_name='Tipo de cuestionario')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombres_principal', models.CharField(max_length=100)),
                ('apellidos_principal', models.CharField(max_length=100)),
                ('cargo_principal', models.CharField(max_length=100)),
                ('institucion_principal', models.CharField(max_length=100)),
                ('ciudad_principal', models.CharField(max_length=100)),
                ('pais_principal', models.CharField(max_length=100)),
                ('rol_estudio_principal', models.CharField(max_length=200)),
                ('email_principal', models.EmailField(max_length=254)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('nombres_alterno', models.CharField(max_length=100)),
                ('apellidos_alterno', models.CharField(max_length=100)),
                ('cargo_alterno', models.CharField(max_length=100)),
                ('institucion_alterno', models.CharField(max_length=100)),
                ('ciudad_alterno', models.CharField(max_length=100)),
                ('pais_alterno', models.CharField(max_length=100)),
                ('rol_estudio_alterno', models.CharField(max_length=200)),
                ('email_alterno', models.EmailField(max_length=254)),
                ('telefono_alterno', models.CharField(max_length=20)),
                ('uso_curricular', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=3)),
                ('carrera_posgrado', models.CharField(blank=True, max_length=200)),
                ('estudiantes', models.CharField(blank=True, max_length=200)),
                ('responsables_orientacion', models.CharField(blank=True, max_length=200)),
                ('titulo_estudio', models.CharField(max_length=200)),
                ('objetivo', models.TextField(max_length=500)),
                ('descripcion_metodologia', models.TextField(max_length=1500)),
                ('caracteristicas_poblacion', models.TextField(max_length=500)),
                ('utilidad_estudio', models.CharField(max_length=500)),
                ('institucion_avala', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
