# Generated by Django 5.0.8 on 2025-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_cuestionario',
            field=models.CharField(choices=[('KIDSCREEN', 'KIDSCREEN: Genérico de CVRS en niñas, niños y jóvenes'), ('CP-QOL', 'CP-QOL: CVRS en personas con discapacidad motora'), ('TWVQ-AR', 'TWVQ-AR: Percepción de la voz y vivencias de mujeres trans'), ('VRBQ', 'VRBQ: Evaluación de rehabilitación de trastornos vestibulares')], default='KIDSCREEN', max_length=20, verbose_name='Tipo de cuestionario'),
        ),
    ]
