version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file: "./app/.env"
    #  - path: ./app/.env
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    env_file: "./app/.env"
    #  - path: ./app/.env
    environment:
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DJANGO_DB_PORT}:${DJANGO_DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d # Mapeo del directorio de configuraciones adicionales
      - static_volume:/app/staticfiles            # Mapeo para archivos estáticos
      - media_volume:/app/media              # Mapeo para archivos multimedia
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
