# Generated by Django 5.0.2 on 2024-04-10 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud_gral', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('suenio', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('cuanto_dolor', models.IntegerField(choices=[(1, 'Nada de dolor'), (2, 'Nada de dolor'), (3, 'Nada de dolor'), (4, 'Nada de dolor'), (5, 'Nada de dolor'), (6, 'Mucho dolor'), (7, 'Mucho dolor'), (8, 'Mucho dolor'), (9, 'Mucho dolor')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('nivel_dolor', models.IntegerField(choices=[(1, 'Nada molesto'), (2, 'Nada molestor'), (3, 'Nada molestor'), (4, 'Nada molesto'), (5, 'Muy molesto'), (6, 'Muy molesto'), (7, 'Muy molesto'), (8, 'Muy molesto'), (9, 'Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('nivel_incomodidad', models.IntegerField(choices=[(1, 'Nada molesto'), (2, 'Nada molestor'), (3, 'Nada molestor'), (4, 'Nada molesto'), (5, 'Muy molesto'), (6, 'Muy molesto'), (7, 'Muy molesto'), (8, 'Muy molesto'), (9, 'Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('como_afecta', models.IntegerField(choices=[(1, 'Nada molesto'), (2, 'Nada molestor'), (3, 'Nada molestor'), (4, 'Nada molesto'), (5, 'Muy molesto'), (6, 'Muy molesto'), (7, 'Muy molesto'), (8, 'Muy molesto'), (9, 'Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('impedimentos', models.IntegerField(choices=[(1, 'Nada molesto'), (2, 'Nada molestor'), (3, 'Nada molestor'), (4, 'Nada molesto'), (5, 'Muy molesto'), (6, 'Muy molesto'), (7, 'Muy molesto'), (8, 'Muy molesto'), (9, 'Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('no_disfrutar_dia', models.IntegerField(choices=[(1, 'Nada molesto'), (2, 'Nada molestor'), (3, 'Nada molestor'), (4, 'Nada molesto'), (5, 'Muy molesto'), (6, 'Muy molesto'), (7, 'Muy molesto'), (8, 'Muy molesto'), (9, 'Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otros_chicos_escuela', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('como_lo_integran', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('profesores', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('otros_alumnos', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('otros_docentes', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('mismo_trato', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('participacion_colegio', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoyo_flia', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('viaje_flia', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('aceptacion_flia', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('mujer', 'Mujer'), ('varon', 'Varón'), ('otro', 'Otro')], max_length=20)),
                ('provincia', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('obra_social', models.CharField(blank=True, max_length=30, null=True)),
                ('prepaga', models.CharField(blank=True, max_length=30, null=True)),
                ('servicio_publico', models.CharField(blank=True, max_length=30, null=True)),
                ('movimiento', models.IntegerField(choices=[(1, 'Tiene dificultad para mantenerse sentado y para poder controlar la cabeza y el tronco en cualquier posición.'), (2, 'Puede mantenerse sentado con algún soporte en pelvis o en tronco, pero no estar de pie, ni caminar sin gran ayuda.'), (3, 'Es capaz de mantenerse de pie por sí mismo y de caminar, sólo si usa alguna ayuda para la marcha (como un andador, muletas, bastones, etc.)'), (4, 'Puede caminar sin ayudas para la marcha, pero necesita apoyarse en el pasamano para subir y bajar escaleras.'), (5, 'Puede caminar sin ayudas para la marcha y subir y bajar escaleras sin necesidad de apoyarse en el pasamano.')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recreativas', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('deportivas', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('eventos_sociales', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('en_su_comunidad', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Relaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_gente', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('otros_chichos', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('con_adultos', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('con_amigos', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('aceptacion_otros_chicos', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('aceptacion_adultos', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('aceptacion_gente', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('cosas_nuevas', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('comunicacion_conocidos', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('comunicacion_extranios', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('comunicacion_otros_con_el', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('comunicacion_tecnologia', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hacer_cosas_solo', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('movilidad', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('independencia', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('moverse_dentro_barrio', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('transporte', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('brazos_y_manos', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('piernas', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('vestirse', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('beber', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('ir_al_banio', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Sentimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hacer_cosas', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('uno_mismo', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('motivacion', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('oportunidades', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('aspecto_fisico', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso_tratamiento', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('acceso_terapia', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('acceso_atencion_medica', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('acceso_pediatria', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('acceso_ayuda_aprendizaje', models.IntegerField(choices=[(1, 'Muy Desconforme'), (2, 'Muy Desconforme'), (3, 'Desconforme'), (4, 'Desconforme'), (5, 'Ni conforme ni desconforme'), (6, 'Ni conforme ni desconforme'), (7, 'Conforme'), (8, 'Conforme'), (9, 'Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('relacion', models.CharField(max_length=50)),
                ('quien_cuida', models.CharField(max_length=100)),
                ('estudios_alcanzados', models.CharField(max_length=100)),
                ('estado_salud', models.CharField(choices=[('excelente', 'Excelente'), ('muy-buena', 'Muy buena'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cpqol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dolor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.dolor')),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.escuela')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.familia')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.paciente')),
                ('participacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.participacion')),
                ('relaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.relaciones')),
                ('salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.salud')),
                ('sentimientos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sentimientos')),
                ('servicios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.servicios')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tutor')),
            ],
        ),
    ]
