# Generated by Django 5.0.8 on 2025-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='promedio',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='estudios_alcanzados',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cobertura_cual',
            field=models.CharField(blank=True, default='---', max_length=100, null=True, verbose_name="¿Cuál? (Responder solo en caso de haber seleccionado 'obra social', 'prepaga a través de obra social' o 'prepaga por contratación voluntaria')"),
        ),
    ]
