# Generated by Django 5.0.8 on 2024-08-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero_otro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='¿Cuál?'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='genero_otro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='¿Cuál?'),
        ),
    ]
