# Generated by Django 5.0.2 on 2024-07-25 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpqol',
            options={'verbose_name_plural': 'Lista De Formularios'},
        ),
        migrations.AlterField(
            model_name='dolor',
            name='como_afecta',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente su hijo/a con respecto a la forma en que los dolores le afectan en su vida?'),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='cuanto_dolor',
            field=models.IntegerField(choices=[(1, '1 - Nada de dolor'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Mucho dolor')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cuánto dolor siente su hijo/a?'),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='impedimentos',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente su hijo/a con respecto a la forma en que el dolor le impide ser él/ella mismo/a?'),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='nivel_dolor',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente su hijo/a con respecto a el nivel de dolor que siente?'),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='nivel_incomodidad',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente su hijo/a con respecto a el nivel de incomodidad que siente?'),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='no_disfrutar_dia',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente su hijo/a con respecto a como el dolor no le permite pasarlo bien todos los días?'),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='salud_gral',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su salud en general?'),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='suenio',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo duerme?'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='como_lo_integran',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo otros alumnos lo/la integran en la escuela o colegio?'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='mismo_trato',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a ser tratado/a de la misma manera que los demás en la escuela o colegio?'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='otros_alumnos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo es aceptado/a por otros alumnos en la escuela o colegio?'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='otros_chicos_escuela',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo se lleva con otros chicos en la escuela o colegio?'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='otros_docentes',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo es aceptado/a por el personal y los docentes de su escuela o colegio?'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='participacion_colegio',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para participar en la escuela o colegio?'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='profesores',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo se lleva con sus maestros, profesores y/o asistentes?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='aceptacion_flia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo es aceptado/a por su familia?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='apoyo_flia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a el apoyo que tiene de su familia?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='viaje_flia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a salir de viaje con la familia?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(max_length=30, verbose_name='Lugar de residencia: [Ciudad]'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad: [Del niño/a o adolescente]'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='deportivas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su habilidad para participar en actividades deportivas? (Esta pregunta refiere a cómo se siente su hijo/a acerca de su habilidad para hacer deporte, no si puede hacerlo o no)'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='en_su_comunidad',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para participar en su comunidad?'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='eventos_sociales',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para participar en eventos sociales fuera de la escuela o colegio?'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='recreativas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para participar en actividades recreativas y de tiempo libre?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='aceptacion_adultos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo es aceptado/a por los adultos?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='aceptacion_gente',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo es aceptado por la gente en general?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='aceptacion_otros_chicos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo es aceptado/a por otros chicos fuera de la escuela o el colegio (que no son sus amigos de la escuela/colegio)?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='comunicacion_conocidos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a la forma en que se comunica con la gente que conoce bien?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='comunicacion_extranios',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a la forma en que se comunica con la gente que NO conoce bien?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='comunicacion_otros_con_el',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a la forma en que otra gente se comunica con su hijo/a?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='comunicacion_tecnologia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a la forma en que se comunica con la gente utilizando tecnología? (por ejemplo, mensajes de texto, internet)?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='con_adultos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo se lleva con los adultos?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='con_amigos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a juntarse con amigos/as?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='con_gente',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo se lleva con la gente en general?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='cosas_nuevas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a la forma en que intenta probar cosas nuevas?'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='otros_chichos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a cómo se lleva con otros chicos fuera de la escuela o el colegio (que no son sus amigos de la escuela/colegio)?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='beber',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para beber sin ayuda?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='brazos_y_manos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su forma de usar sus brazos y sus manos?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='hacer_cosas_solo',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a hacer cosas solo/a, sin compañía?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='independencia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a poder hacer cosas solo/a sin depender de otros?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='ir_al_banio',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para ir al baño sin ayuda?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='moverse_dentro_barrio',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para moverse dentro de su barrio?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='movilidad',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su forma de trasladarse de un lado a otro? (es decir, su movilidad)?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='piernas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su forma de usar sus piernas?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='transporte',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para ir de un lugar a otro (ej. transporte)?'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='vestirse',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para vestirse sólo/a?'),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='aspecto_fisico',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su aspecto físico?'),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='hacer_cosas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su capacidad para hacer las cosas que quiere hacer?'),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='motivacion',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a su motivación?'),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='oportunidades',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a sus oportunidades en la vida?'),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='uno_mismo',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo piensa que su hijo/a se siente con respecto a él/ella mismo/a?'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_atencion_medica',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente USTED con respecto a el acceso a atención médica o quirúrgica especializada?'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_ayuda_aprendizaje',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente USTED con respecto a el acceso a ayuda adicional de aprendizaje dentro de la escuela o colegio?'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_pediatria',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente USTED con respecto a el acceso a atención de pediatría o medicina general?'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_terapia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente USTED con respecto a el acceso de su hijo/a a terapia (por ejemplo: fisioterapia, fonoaudiología, terapia ocupacional)?'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_tratamiento',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='¿Cómo se siente USTED con respecto a el acceso de su hijo/a al tratamiento?'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='estado_salud',
            field=models.CharField(choices=[('mala', 'Mala'), ('regular', 'Regular'), ('buena', 'Buena'), ('muy-buena', 'Muy buena'), ('excelente', 'Excelente')], max_length=20, verbose_name='Usted diría que SU SALUD es: [De la persona que responde]'),
        ),
    ]
