# Generated by Django 5.0.2 on 2024-04-22 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_paciente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolor',
            name='como_afecta',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2 - Nada molestor'), (3, '3 - Nada molestor'), (4, '4 - Nada molesto'), (5, '5 - Muy molesto'), (6, '6 - Muy molesto'), (7, '7 - Muy molesto'), (8, '8 - Muy molesto'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='cuanto_dolor',
            field=models.IntegerField(choices=[(1, '1 - Nada de dolor'), (2, '2 - Nada de dolor'), (3, '3 - Nada de dolor'), (4, '4 - Nada de dolor'), (5, '5 - Nada de dolor'), (6, '6 - Mucho dolor'), (7, '7 - Mucho dolor'), (8, '8 - Mucho dolor'), (9, '9 - Mucho dolor')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='impedimentos',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2 - Nada molestor'), (3, '3 - Nada molestor'), (4, '4 - Nada molesto'), (5, '5 - Muy molesto'), (6, '6 - Muy molesto'), (7, '7 - Muy molesto'), (8, '8 - Muy molesto'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='nivel_dolor',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2 - Nada molestor'), (3, '3 - Nada molestor'), (4, '4 - Nada molesto'), (5, '5 - Muy molesto'), (6, '6 - Muy molesto'), (7, '7 - Muy molesto'), (8, '8 - Muy molesto'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='nivel_incomodidad',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2 - Nada molestor'), (3, '3 - Nada molestor'), (4, '4 - Nada molesto'), (5, '5 - Muy molesto'), (6, '6 - Muy molesto'), (7, '7 - Muy molesto'), (8, '8 - Muy molesto'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='no_disfrutar_dia',
            field=models.IntegerField(choices=[(1, '1 - Nada molesto'), (2, '2 - Nada molestor'), (3, '3 - Nada molestor'), (4, '4 - Nada molesto'), (5, '5 - Muy molesto'), (6, '6 - Muy molesto'), (7, '7 - Muy molesto'), (8, '8 - Muy molesto'), (9, '9 - Muy molesto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='salud_gral',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='dolor',
            name='suenio',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='como_lo_integran',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='mismo_trato',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='otros_alumnos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='otros_chicos_escuela',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='otros_docentes',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='participacion_colegio',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='profesores',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='familia',
            name='aceptacion_flia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='familia',
            name='apoyo_flia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='familia',
            name='viaje_flia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='deportivas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='en_su_comunidad',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='eventos_sociales',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='recreativas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='aceptacion_adultos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='aceptacion_gente',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='aceptacion_otros_chicos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='comunicacion_conocidos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='comunicacion_extranios',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='comunicacion_otros_con_el',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='comunicacion_tecnologia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='con_adultos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='con_amigos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='con_gente',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='cosas_nuevas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='otros_chichos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='beber',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='brazos_y_manos',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='hacer_cosas_solo',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='independencia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='ir_al_banio',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='moverse_dentro_barrio',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='movilidad',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='piernas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='transporte',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='salud',
            name='vestirse',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='aspecto_fisico',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='hacer_cosas',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='motivacion',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='oportunidades',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='sentimientos',
            name='uno_mismo',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_atencion_medica',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_ayuda_aprendizaje',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_pediatria',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_terapia',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='acceso_tratamiento',
            field=models.IntegerField(choices=[(1, '1 - Muy Desconforme'), (2, '2 - Muy Desconforme'), (3, '3 - Desconforme'), (4, '4 - Desconforme'), (5, '5 - Ni conforme ni desconforme'), (6, '6 - Ni conforme ni desconforme'), (7, '7 - Conforme'), (8, '8 - Conforme'), (9, '9 - Muy Conforme')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
