# Generated by Django 5.0.8 on 2025-02-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_saludultimasemana2_atencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='atencion',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿El chico/a pudo prestar atención en clase?'),
        ),
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='colegio',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿Al chico/a le fue bien en la escuela o en el colegio?'),
        ),
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='cosas_queria',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿El chico/a hizo las cosas que quería hacer en su tiempo libre?'),
        ),
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='diversion',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿El chico/a se divirtió con sus amigos/as?'),
        ),
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='energia',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿El chico/a se sintió lleno/a de energía?'),
        ),
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='fisicamente',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿El chico/a se sintió bien y físicamente en forma?'),
        ),
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='justicia',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿Los padres del chico/a fueron justos con él/ella?'),
        ),
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='soledad',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿El chico/a se sintió solo/a?'),
        ),
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='tiempo_libre',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿El chico/a tuvo suficiente tiempo para él/ella?'),
        ),
        migrations.AlterField(
            model_name='saludultimasemana2',
            name='tristeza',
            field=models.CharField(choices=[('Nada', 'Nada'), ('Muchísimo', 'Muchísimo'), ('Un poco', 'Un poco'), ('Moderadamente', 'Moderadamente'), ('Mucho', 'Mucho')], max_length=100, verbose_name='¿El chico/a se sintió triste?'),
        ),
    ]
